apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-rest-api.fullname" . }}
  labels:
    {{- include "test-rest-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "test-rest-api.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    {{- if .Values.tls.enabled }}
    - name: https
      port: {{ .Values.tls.port }}
      targetPort: https
    {{- end }}
